name: create-release

on:
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Install
        shell: bash
        run: |
          yarn install
          yarn build
      
      - uses: Actions-R-Us/actions-tagger@latest
        with:
          publish_latest_tag: false
